en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Company Name. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Site Title"
  params:
    description: "Site Description"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Join"
      link: "/example-page/"
    footer_cta:
      text: "Join us"
      link: "/example-page/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "data"
      name: "data"
      url: "/about/data/"
      parent: "about"
      weight: 1
    - identifier: "configuration"
      name: "Configuration"
      url: "/about/configuration/"
      weight: 2
      parent: "about"
    - identifier: "articles"
      name: "Articles"
      url: "/articles/"
      weight: 2
    - identifier: "technical-articles"
      name: "Technical"
      url: "/articles/technical"
      parent: "articles"
      weight: 2
    - identifier: "sailing-articles"
      name: "Sailing"
      url: "/articles/sailing"
      parent: "articles"
      weight: 1
    - identifier: "logs"
      name: "Logs"
      url: "/logs/"
      weight: 4
    - identifier: "technical-logs"
      name: "Technical"
      url: "/logs/technical"
      parent: "logs"
      weight: 2
    - identifier: "sailing-logs"
      name: "Sailing"
      url: "/logs/sailing"
      parent: "logs"
      weight: 1