######################## production configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL: http://GBR5338L.info
googleAnalytics:
enableRobotsTXT: true
build:
  writeStats: true
